# Generated by Django 2.0.9 on 2018-12-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181114_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ('user',)},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='region',
            field=models.CharField(max_length=50),
        ),
    ]
